export { default as LandingPage } from './LandingPage'
export { default as PlansPage } from './PlansPage'
export { default as PlanDetailPage } from './PlanDetailPage'
export { default as PlanCheckoutPage } from './PlanCheckoutPage'
export { default as TermsAndConditionsPage } from './TermsAndConditionsPage'
export { default as ContactUsPage } from './ContactUsPage'
export { default as AboutUsPage } from './AboutUsPage'
